import { Comfortaa } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "../styles/globals.css";
import "../styles/fonts.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const comdfortaa = Comfortaa({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={comdfortaa.className}>{children}</body>
    </html>
  );
}
